
# environment tag that will be registered on consul to support multiple instances per env for testing.
# https://github.com/networknt/light-doc/blob/master/docs/content/design/env-segregation.md
# This tag should only be set for testing env, not production. The production certification process will enforce it.
server.environment: dev

# Build number, to be set by teams for auditing purposes. 
# Allows teams to audit the value and set it according to their release management processes
server.buildNumber: latest

#--------------------------------------------------------------------------------
# security.yml
#--------------------------------------------------------------------------------
# Enable JWT verification flag.
# security.enableVerifyJwt: true

#--------------------------------------------------------------------------------
# datasource.yml
#--------------------------------------------------------------------------------

datasource.H2DataSource:
  DriverClassName: org.h2.jdbcx.JdbcDataSource
  jdbcUrl: jdbc:h2:mem:testdb;INIT=runscript from 'classpath:scripts/schema.sql';
  username: sa
  password: sa
  maximumPoolSize: 2
  connectionTimeout: 1000
